### ISSUE TITLE
Requiring vue-quill-editor/dist/ssr: document is not defined

### ISSUE THREAD

**Issue by Linzdigr** [surmon-china/vue-quill-editor#122]
On vue-quill-editor 3.0.3, require vue-quill-editor/dist/ssr when rendering on server side results in 

```
ReferenceError: document is not defined
    at Object.DIFF_DELETE ([...]/foo/node_modules/quill/dist/quill.js:7450:21)
    at __webpack_require__ ([...]/foo/node_modules/quill/dist/quill.js:36:30)
    at Object.defineProperty.value ([...]/foo/node_modules/quill/dist/quill.js:975:1)
    at __webpack_require__ ([...]/foo/node_modules/quill/dist/quill.js:36:30)
    at Object.defineProperty.value ([...]/foo/node_modules/quill/dist/quill.js:4988:14)
    at __webpack_require__ ([...]/foo/node_modules/quill/dist/quill.js:36:30)
    at Object.defineProperty.value ([...]/foo/node_modules/quill/dist/quill.js:9832:13)
    at __webpack_require__ ([...]/foo/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> ([...]/foo/node_modules/quill/dist/quill.js:11344:18)
    at __webpack_require__ ([...]/foo/node_modules/quill/dist/quill.js:36:30)
```

```vue.js
let VueQuillEditor

if(!Vue.prototype.$isServer) {
    VueQuillEditor = require('vue-quill-editor')
} else {
    VueQuillEditor = require('vue-quill-editor/dist/ssr')
}

Vue.use(VueQuillEditor)
```

Could you enlighten me if I'm missing something?

**Comment by surmon-china** [comment]
In ssr you just use it with SSR(directive), can't use component.

```javascript
let VueQuillEditor

if(Vue.prototype.$isServer) {
    VueQuillEditor = require('vue-quill-editor/dist/ssr')
}

Vue.use(VueQuillEditor)
```

```html
<div v-quill="quillOption"></div>
```

**Comment by Linzdigr** [comment]
Sorry forgot to point out I already use directive.

**Comment by Linzdigr** [comment]
Still on the same point, any advice?

**Comment by surmon-china** [comment]
1. If used in SSR mode, you must only import `vue-quill-editor/dist/ssr`, can not import any file that depends on the window object

2. Must be imported in browser-loaded mode

let VueQuillEditor

`Vue.prototype.$isServer` is not ssr

`process.browser` is ssr and browser

**Comment by Linzdigr** [comment]
The following code still produce the same error (with 3.0.4):

```vue.js
let VueQuillEditor

if(process.browser) {
    VueQuillEditor = require('vue-quill-editor')
} else {
    VueQuillEditor = require('vue-quill-editor/dist/ssr')
}

Vue.use(VueQuillEditor)
```
and the component vue-quill-editor part:
```html
    <template v-if="process.browser">
        <quill-editor
            v-model="currentEdition.text"
            ref="myQuillEditor"
            :options="editorOption">
        </quill-editor>
    </template>
    <div v-else
        class="quill-editor"
        v-model="content"
        ref="myQuillEditor"
        v-quill:myQuillEditor="currentEdition.text">
    </div>
```

**Comment by surmon-china** [comment]
I do not think you understand how webpack and ssr work together, so it's hard to explain; all you need to know is that everything you have to do with SSR when using SSR rendering output.

**In a program involving SSR rendering, you can not use components, you can only use `vue-quill-editor/dist/ssr`**

**Comment by outOFFspace** [comment]
That's because of 
`var _quill = require('quill');
`
It uses document
