### ISSUE TITLE
Webpack: Module build failed

### ISSUE THREAD

**Issue by d3radicated** [surmon-china/vue-quill-editor#44]
I'm using `laravel-mix` to build my files. I updated to the recent version and encountered this error while building.

```
Module build failed: Error: Couldn't find preset "es2015" relative to directory "C:\\Work\\XXX\\node_modules\\vue-quill-editor"
    at C:\Work\XXX\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (C:\Work\XXX\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\Work\XXX\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\Work\XXX\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\Work\XXX\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\Work\XXX\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Work\XXX\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Work\XXX\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Work\XXX\node_modules\babel-loader\lib\index.js:46:20)
    at C:\Work\XXX\node_modules\babel-loader\lib\fs-cache.js:79:18
    at ReadFileContext.callback (C:\Work\XXX\node_modules\babel-loader\lib\fs-cache.js:15:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:358:13)

 @ ./~/vue-quill-editor/src/editor.vue 7:2-214
 @ ./~/vue-quill-editor/src/index.js
 @ ./resources/assets/control-panel/app.js
 @ multi ./resources/assets/control-panel/app.js
```

Deleting `.babelrc` seems to solve the issue.

**Comment by surmon-china** [comment]
Thank you for your feedback, I will seriously check this question!

**Comment by surmon-china** [comment]
@d3radicated Hi! I want to reproduce this problem, can you tell me how you are using it, is the form of using SPA components, or the introduction of compiled js files?

**Comment by jkchao** [comment]
@surmon-china  Hi, I have the same problem, form of using SPA components.

**Comment by d3radicated** [comment]
Same with @jkchao, I'm using SPA components with it.

**Comment by surmon-china** [comment]
I will fix it!

**Comment by surmon-china** [comment]
Try v2.1.6, it should be work!
@d3radicated @jkchao

**Comment by d3radicated** [comment]
Seems there's no other way than deleting `.babelrc`. Other than that, it works. Thanks. 😊

**Comment by surmon-china** [comment]
Enjoy your job!😆
