### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'register')

### ISSUE THREAD

**Issue by LXCGH** [surmon-china/vue-quill-editor#482]
### Describe the bug

I can run ‘vue-quill-editor’ by using vue-cli4.5.13，However, the following error is reported when installing 'quick image resize module':
quill.js?9339:1122 Uncaught TypeError: Cannot read properties of undefined (reading 'register')
    at Function.register (quill.js?9339:1122:1)
    at eval (main.js?56d7:18:1)
    at ./src/main.js (app.js:1147:1)
    at __webpack_require__ (app.js:859:30)
    at fn (app.js:151:20)
    at 1 (app.js:1256:18)
    at __webpack_require__ (app.js:859:30)
    at checkDeferredModules (app.js:46:23)
    at app.js:1040:18
    at app.js:1043:10
![error](https://user-images.githubusercontent.com/16572591/191400541-f03460db-97d1-47b3-88ec-89a3f5602ad3.png)

### Reproduction

quill.js?9339:1122 Uncaught TypeError: Cannot read properties of undefined (reading 'register')
    at Function.register (quill.js?9339:1122:1)
    at eval (main.js?56d7:18:1)
    at ./src/main.js (app.js:1147:1)
    at __webpack_require__ (app.js:859:30)
    at fn (app.js:151:20)
    at 1 (app.js:1256:18)
    at __webpack_require__ (app.js:859:30)
    at checkDeferredModules (app.js:46:23)
    at app.js:1040:18
    at app.js:1043:10

### System Info

```shell
"vue-quill-editor": "^3.0.6",
"quill-image-resize-module": "^3.0.0",

main.js
import VueQuillEditor, { Quill } from 'vue-quill-editor'
import { ImageResize } from 'quill-image-resize-module'
Quill.register('modules/imageResize', ImageResize)
Vue.use(VueQuillEditor)

vue.config.js
config.plugin("provide").use(webpack.ProvidePlugin, [
      {
        "window.Quill": "quill/dist/quill.js",
        Quill: "quill/dist/quill.js",
      },
    ]);
```

### Used Package Manager

npm

### Validations

- [X] Read the the documentation in detail.
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a GitHub Discussion or join our [Discord Chat Server](https://discord.surmon.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by LXCGH** [comment]
I have a problem with my writing
