### ISSUE TITLE
在VueJs中引入直接报错？

### ISSUE THREAD

**Issue by huangche007** [surmon-china/vue-quill-editor#61]
./~/_babel-loader@6.4.1@babel-loader/lib!./~/_vue-loader@12.2.1@vue-loader/lib/selector.js?type=script&index=0!./~/_vue-quill-editor@2.2.2@vue-quill-editor/src/editor.vue
Module build failed: TypeError: D:/Products/ecmagnet-mobile/node_modules/_vue-quill-editor@2.2.2@vue-quill-editor/src/editor.vue: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null
    at Object.validate (D:\Products\ecmagnet-mobile\node_modules\_babel-types@6.24.1@babel-types\lib\definitions\index.js:109:13)
    at Object.validate (D:\Products\ecmagnet-mobile\node_modules\_babel-types@6.24.1@babel-types\lib\index.js:505:9)
    at NodePath._replaceWith (D:\Products\ecmagnet-mobile\node_modules\_babel-traverse@6.24.1@babel-traverse\lib\path\replacement.js:176:7)
    at NodePath._remove (D:\Products\ecmagnet-mobile\node_modules\_babel-traverse@6.24.1@babel-traverse\lib\path\removal.js:58:10)
    at NodePath.remove (D:\Products\ecmagnet-mobile\node_modules\_babel-traverse@6.24.1@babel-traverse\lib\path\removal.js:30:8)
    at PluginPass.CallExpression (D:\Products\ecmagnet-mobile\node_modules\_babel-plugin-transform-es2015-modules-amd@6.24.1@babel-plugin-transform-es2015-modules-amd\lib\index.js:42:12)
    at NodePath._call (D:\Products\ecmagnet-mobile\node_modules\_babel-traverse@6.24.1@babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (D:\Products\ecmagnet-mobile\node_modules\_babel-traverse@6.24.1@babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (D:\Products\ecmagnet-mobile\node_modules\_babel-traverse@6.24.1@babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (D:\Products\ecmagnet-mobile\node_modules\_babel-traverse@6.24.1@babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (D:\Products\ecmagnet-mobile\node_modules\_babel-traverse@6.24.1@babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (D:\Products\ecmagnet-mobile\node_modules\_babel-traverse@6.24.1@babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (D:\Products\ecmagnet-mobile\node_modules\_babel-traverse@6.24.1@babel-traverse\lib\index.js:114:17)
    at NodePath.visit (D:\Products\ecmagnet-mobile\node_modules\_babel-traverse@6.24.1@babel-traverse\lib\path\context.js:115:19)
    at TraversalContext.visitQueue (D:\Products\ecmagnet-mobile\node_modules\_babel-traverse@6.24.1@babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (D:\Products\ecmagnet-mobile\node_modules\_babel-traverse@6.24.1@babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (D:\Products\ecmagnet-mobile\node_modules\_babel-traverse@6.24.1@babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (D:\Products\ecmagnet-mobile\node_modules\_babel-traverse@6.24.1@babel-traverse\lib\index.js:114:17)
 @ ./~/_vue-quill-editor@2.2.2@vue-quill-editor/src/editor.vue 8:2-109
 @ ./~/_vue-quill-editor@2.2.2@vue-quill-editor/src/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

**Comment by surmon-china** [comment]
请升级到最新版，若还有问题则重新开启问题。
